#!/usr/bin/env node
'use strict'

const CONFIG = require('./config')
const dependenciesFingerprint = require('./lib/dependencies-fingerprint')

process.on('unhandledRejection', function (e) {
  console.error(e.stack || e)
  process.exit(1)
});

// We can't use yargs until installScriptDependencies() is executed, so...
let ci = process.argv.indexOf('--ci') !== -1

if (!ci && process.env.CI === 'true' && process.argv.indexOf('--no-ci') === -1) {
  console.log('Automatically enabling --ci because CI is set in the environment');
  ci = true;
}

require('./lib/verify-machine-requirements').start(ci);

if (dependenciesFingerprint.isOutdated()) {
  require('./lib/clean-dependencies').start();
}

if (process.platform === 'win32') require('./lib/delete-msbuild-from-path').start();

require('./lib/install-script-dependencies').start(ci);
require('./lib/install-apm').start(ci);
require('./lib/run-apm-install').start(CONFIG.repositoryRootPath, ci);

dependenciesFingerprint.write();
