#!/usr/bin/env node
'use strict'

require('./lib/kill-running-atom-instances').start()
require('./lib/clean-dependencies').start()
require('./lib/clean-caches').start()
require('./lib/clean-output-directory').start()
